import "@/app/globals.css"
import { Metadata } from "next"

export const metadata: Metadata = {
  title: "Nija Dashboard",
  description: "Generated by create next app",
  icons: {
    icon: "./favicon.ico"
  }
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={`UI-Ecommerce`}>{children}</body>
    </html>
  )
}
