
import "@/app/globals.css"
import { Sidebar, Topbar } from "@/components/organisms"
import ClientLayout from "./ClientLayout"
export const metadata = {
  title: 'VEMORA SHOPING',
  description: 'Generated by create next app',
  other: {
    'msapplication-TileColor': '#000000',
    'apple-touch-fullscreen': 'yes',
  },
}


export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {

  return (
    <ClientLayout>
  <html lang='en'>
  <head>
  <link rel="icon" href="/favicon.ico" />
</head>
     <body className={`UI-Ecommerce`} suppressHydrationWarning={true}>
       <div className='fixed left-0 top-0 z-10 w-64 2xl:w-72'>
         <Sidebar />
       </div>

       <div className='fixed inset-0 z-10 ml-64 h-20 w-[calc(100vw_-_256px)] 2xl:ml-72 2xl:w-[calc(100vw_-_288px)]'>
         <Topbar />
       </div>

       <main className='relative z-0 min-h-screen bg-netral-20/50 pl-64 pt-20 2xl:pl-72'>
         {children}
       </main>
     </body>
   </html>
    </ClientLayout>
   
  )
}
