import "@/app/globals.css"

import { Plus_Jakarta_Sans } from "next/font/google"

const jakarta = Plus_Jakarta_Sans({ subsets: ["latin"] })

export const metadata = {
  title: "VEMORA",
  description: "Generated by create next app",
 
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={`UI-Ecommerce`}>{children}</body>
    </html>
  )
}
